config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
 
  # get '/:song_name' => 'songs#show'
  resources :songs, :path => ''

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord


	def to_param
		song_name
	end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def change_song
    @last_song = @song
    redirect_url root
  end

  helper_method :change_song
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController 

	def index
		
		@last_song = Song.last
		@songs = Song.where.not(id: @last_song.id)
	end 
end 

app/controllers/songs_controller.rb
class SongsController < ApplicationController 



	def show 
		@last_song = Song.find_by(song_name: params[:id])
		@songs = Song.where.not(id: @last_song.id)	
	end


	def create 
		@song = Song.new(song_params)
		@song.song_name.gsub(/[.\/,&()]/, '').gsub(/[\s\-]+/, '-') 
		if @song.save 
			redirect_url root 
		end
	end 

	def new 
		@song = Song.new 
	end 


	def song_params
		params.require(:song).permit(:song_artist, :song_name, :song_link, :song_artwork)
	end 

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landing/_next.html.slim
.next-songs 
	.next-container 
		p Explore New Music
		- @songs.each do |song| 
			.box 
				.image
					= link_to image_tag("#{song.song_artwork}"), song_path(song)
				.content 	
					p.artist = song.song_artist
					p.song = song.song_name.gsub(/[.\/,&()]/, '').gsub(/[\s\-]+/, ' ')  

app/views/landing/_player.html.slim
.player-section
	.artwork 
		.image 
			= image_tag("#{@last_song.song_artwork}")
	.player
		.track#info 
			.artist-name
				p = @last_song.song_artist   
			.song-name
				p = @last_song.song_name.gsub(/[.\/,()]/, '').gsub(/[\s\-]+/, ' ')  

		audio id="player" ontimeupdate="udpateProgress()" src="#{@last_song.song_link}"	
		progress id="seekbar" value='0' max="1"
		.pause 
			i.far.fa-play-circle.fa-4x#play
	hr
	= render 'landing/next'

app/views/landing/_upload.html.slim
.upload-section
	.uld-head
		p UPLOAD MUISC
	.form
		.input#list
			ul 
				li.field 
					 input type="text" name="Artist Name" placeholder="Artist Name" class="type-in"
				li.field 
					input type="text" name="Song Name" placeholder="Track Name" class="type-in"
				li.field 
					input type='file' name="Song" placeholder="Song"
		.input#submit-button 
				a href="#" 
					i.far.fa-play-circle.fa-4x
				
		hr 
		.social-media
			ul 
				li 
					i.fab.fa-twitter
				li
					i.fab.fa-facebook
				li 
					i.fab.fa-instagram
				li
					i.fab.fa-youtube

app/views/landing/index.html.slim
.container 
	.frame
		= render 'player'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Disqovor
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 
    
    script src='https://use.fontawesome.com/releases/v5.0.6/js/all.js'
	body
		.border 

		.logo 
			p Disqovor 
  	= yield 
  footer 
  	p Disqovor © 2018
  	ul 
  		li 
  			= link_to "Upload", "#", id: 'upload_btn'
  		li 
  			= link_to "Privacy", "#" 
  		li 
  			= link_to "About", "#" 
  		li 
  			= link_to "Terms", "#" 

app/views/songs/show.html.slim
.container 
	.frame
		= render 'landing/player'